name: CI/CD Pipeline for Flask and React

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.8]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pytest mysql-connector-python bcrypt flask flask-jwt-extended flask-cors gunicorn
          pip install -r requirements.txt
        
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node dependencies and build React app
      run: |
        cd react-frontend
        npm install

    - name: Deploy Code to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo mkdir -p /var
          sudo chown -R ubuntu:ubuntu /var
          cd /var
          sudo apt update && sudo apt install -y python3-pip git

          # Install Node Version Manager (NVM)
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install --lts
          nvm use --lts

          # Stop existing services if running
          sudo systemctl stop flask.service || true
          sudo systemctl stop react-frontend.service || true

          # Clone the repository
          if [ -d "deploy-api" ]; then
            echo "Repository already exists. Deleting the existing directory."
            sudo rm -rf deploy-api 
          fi
          sudo git clone https://github.com/manish92596/deploy-api.git deploy
          sudo chown -R ubuntu:ubuntu /var/deploy/deploy-api

          # Update React baseURL
          cd /var/deploy/deploy-api/react-frontend/src/components
          sudo chown ubuntu:ubuntu baseURL.js
          sed -i "s|const BASE_URL = .*;|const BASE_URL = \"http://${{ secrets.REMOTE_HOST }}:5001\";|g" baseURL.js

    - name: Deploy Flask Backend to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/deploy/deploy-api/flask-backend
          sudo chown -R ubuntu:ubuntu /var/deploy/deploy-api/flask-backend
          sudo pip install -r requirements.txt
          sudo systemctl start flask.service

    - name: Start React Development Server on AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/deploy/deploy-api/react-frontend
          sudo chown -R ubuntu:ubuntu /var/deploy/deploy-api/react-frontend
          npm install 
          sudo systemctl start react-frontend.service

    - name: Clean Up Post-Deployment
      run: |
        echo "Deployment completed successfully."
